replicaCount: 2

image:
  repository: cloudlabhost/transporteparatodos
  tag: 9968e834ac17bb30ba26fd02cbf99f275dad4352
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 32329
