replicaCount: 2

image:
  repository: cloudlabhost/transporteparatodos
  tag: bf9c890547954caba38ce3448940dec5f22fd946
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 32329
