replicaCount: 2

image:
  repository: cloudlabhost/transporteparatodos
  tag: b318a5924f28483dc2b4190aaafcde1953e4875c
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 32329
