apiVersion: apps/v1
kind: Deployment
metadata:
  name: transporteparatodos

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: transporteparatodos

  template:
    metadata:
      labels:
        app: transporteparatodos

    spec:
      containers:
        - name: transporteparatodos
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: 80
