name: Build and Deploy Transporte Para Todos

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar codigo
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e Push da imagem
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            cloudlabhost/transporteparatodos:latest
            cloudlabhost/transporteparatodos:${{ github.sha }}

  deploy:
    needs: build
    runs-on: [self-hosted, Linux, X64, transporte]

    steps:
      - name: Atualizar Kubernetes
        run: |
          kubectl set image deployment/transporteparatodos transporteparatodos=cloudlabhost/transporteparatodos:${{ github.sha }}
          kubectl rollout status deployment/transporteparatodos --timeout=120s